<center> <img src="logo_ifba.jpg" alt="jpg_python" width="100" height=""> </center>
<br><br>
<center> <img src="logo_coext.jpg" alt="jpg_python" width="200" height=""> </center>
<br><br>
<center><div style="text-align:center">    <a href="https://colab.research.google.com/github/ProfAllanIFBA/Curso_Python_Com_Jupyter_Notebook/blob/main/Capitulo021_Arrays_Com_Numpy/Capitulo021_Arrays_Com_Numpy.ipynb">Link Colab</a> 
</div><br><br></center>
<div align="center"><span style="font-size: 26px;"><strong>Python Com Jupyter Notebook</strong></span></div><br><br>
<center> <img src="python_gif.gif" alt="gif_python" width="80"> </center>

Este material apresenta uma explicação detalhada sobre o uso do software de programação em Python chamado Jupyter Notebook, com foco na análise de dados. Abordaremos desde estruturas básicas, como listas e dicionários, até estruturas mais complexas voltadas para a análise de dados, como pandas e seaborn, além de ferramentas destinadas à inteligência artificial.


<font color='red'> <u>Este é um material de uso público e totalmente gratuito</u>. Contudo, eventuais edições são de responsabilidade de quem as fizer. </font>

Você pode ajudar a melhorar este material!

Contato e Sugestões: allansoares@ifba.edu.br.

[**Equipe Executora**](https://github.com/ProfAllanIFBA/Curso_Python_Com_Jupyter_Notebook/blob/main/Capitulo000_Equipe/Capitulo000_Equipe.ipynb)

### <center> <font color='red'> Vídeo Aulas <img src="youtube.gif" alt="jpg_python" width="100" height=""> </font> </center>

[Array Com Numpy no Python](https://youtu.be/Yyyk-kbZn3w)

[Indexação de Arrays Com Numpy no Python](https://youtu.be/PjdsL5fwYII)

[Opreações Básicas Com Matrizes Usando Numpy no Python](https://youtu.be/Ko8WaaIqWaE)

[Funções Com Array Usando Numpy no Python - Parte 1](https://youtu.be/9hDjMA8r9_s)

*Os vídeos restantes serão postados assim que possível!*

<div style="border: 2px solid black; padding: 10px; width: 100%; background-color: lightgray; display: flex; align-items: center;">
    <h1 style="color: red; text-align: center; margin: auto;">
        Capítulo 21 - Arrays Com Numpy
    </h1>
</div>

<font color='red'></font>
<a href=""></a>

Os <u>arrays</u> (matrizes) da NumPy, também conhecidos como ndarrays, possuem características que os tornam mais eficientes e versáteis em comparação com as listas tradicionais do Python. Com a NumPy, você pode realizar operações aritméticas em arrays sem a necessidade de loops, o que resulta em um código mais limpo e eficiente.

## <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 22px;"><strong>21.1 Criação de Arrays Com NumPy</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### *Exemplo 1: Criando um vetor*

In [1]:
# Importando a biblioteca numpy com prefixo simplificado np (numpy -> np)
import numpy as np

In [2]:
# Array criado a partir de uma lista Python
vetor = np.array([2,6,7,5])

In [3]:
# Imprimindo a array
print(vetor)

[2 6 7 5]


In [4]:
# Consultando o tipo de objeto
print(type(vetor))

<class 'numpy.ndarray'>


No exemplo acima a variável "vetor" pode ser entendido como um vetor de quatro dimensões.

#### *Exemplo 2: Criando uma matriz*

In [5]:
# Importando a biblioteca numpy
import numpy as np

# Array criado a partir de uma lista de listas Python
matriz = np.array([[-1,3,4], 
                   [2,5,-1]])

In [6]:
# Imprimindo a array2
print(matriz)

[[-1  3  4]
 [ 2  5 -1]]


No exemplo acima a variável "matriz" pode ser entendido como matriz $2 \times 3$ ($2$ linhas e $3$ colunas).

In [7]:
print(type(matriz))

<class 'numpy.ndarray'>


## <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 22px;"><strong>21.2 Indexação de Arrays Com Numpy</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

Assim como as listas em Python, os arrays também permitem acesso fácil aos seus elementos internos. A seguir, apresentaremos algumas formas de acessar os elementos internos de um array.

#### *Exemplo 1: Acessando elementos de uma array de dimensão 1*

As regras para se acessar os elementos de um array de dimensão 1 são semelhantes às usadas para acessar elementos de uma lista.

In [9]:
# Importando a biblioteca numpy com prefixo simplificado np (numpy -> np)
import numpy as np

In [10]:
# Array criado a partir de uma lista Python
array = np.array([-1,3,4,5])

In [13]:
# Imprimindo elementos de um array de dimensão 1
print(array[1])

3


#### *Exemplo 2: Acessando elementos, linhas e colunas de uma array de dimensão 2*

In [14]:
# Importando a biblioteca numpy
import numpy as np

In [16]:
# Array criado a partir de uma lista de listas Python
array = np.array([[-1,3, 4,8],
                  [2 ,5,-1,7],
                  [-1,9, 8,2]])

In [21]:
print(array.ndim)

2


In [17]:
# Imprimindo elementos
print(array[1][1])

5


In [18]:
# Imprimindo linhas
print(array[0])

[-1  3  4  8]


In [19]:
# Imprimindo colunas
print(array[:,3])

[8 7 2]


#### *Exemplo 3: Acessando elementos, matrizes, linha de matrizes e coluna de matrizes de uma array 3.*

In [22]:
# Importando a biblioteca numpy
import numpy as np

In [23]:
# Array criado a partir de uma lista de listas Python
array = np.array([[[-1, 3, 2], 
                   [5, 1, -4]], [[7, -8, 9],
                                [10, 3, 5]], [[13, 14, 1],
                                              [10, 10, 9]]])

In [24]:
array.ndim

3

In [27]:
# Consultar um elemento específico
element = array[1, 1, 1]
print(element)

3


In [28]:
# Consultar uma matriz específica
matrix = array[2]
print(matrix)

[[13 14  1]
 [10 10  9]]


In [29]:
# Consultar uma linha específica em uma matriz
row = array[2, 0]
print(row)

[13 14  1]


In [30]:
# Consultar uma coluna específica em uma matriz
column = array[2, :, 2]
print(column)

[1 9]


In [31]:
# Consultar elementos de posições específicas em cada matriz
pos_especifica = array[:, 0, 1]
print(pos_especifica)

[ 3 -8 14]


#### *Exemplo 4: Acessando multiplos indices simultaneamente (primeira camada)*

Neste exemplo, exploraremos como acessar múltiplos elementos da primeira dimensão. Para um array unidimensional, um elemento da primeira dimensão corresponde a um elemento individual. Em um array bidimensional, um elemento da primeira dimensão é, na verdade, um array unidimensional, enquanto em um array tridimensional, um elemento da primeira dimensão é um array bidimensional. Essas observações são fundamentais para a manipulação eficaz de dados usando arrays NumPy de diferentes dimensões.

In [32]:
# Importando a biblioteca numpy com prefixo simplificado np (numpy -> np)
import numpy as np

In [33]:
# Array de dimensão 1
array1 = np.array([-1,3,4,5])

In [34]:
# Lista de índices
indices1 = [2,0,1]

In [35]:
# Impressão dos índices da lista indices
print(array1[indices1])

[ 4 -1  3]


In [36]:
# Array de dimensão 2
array2 = np.array([[-1,3,4,8],
                  [2,5,-1,7],
                  [-1,9,8,2]])

In [39]:
# Lista de índices
indices2 = [[0],[1]]

# Impressão dos índices da lista indices
print(array2[indices2])

[[[-1  3  4  8]]

 [[ 2  5 -1  7]]]


In [40]:
# Array de dimensão 3
array3 = np.array([[[-1, 3, 2],
                   [5, 1, -4]],[[7, -8, 9],
                                [10, 3, 5]],[[13, 14, 1],
                                             [10, 10, 9]]])

In [41]:
# Lista de índices
indices3 = [[0],[2]]

In [42]:
# Impressão dos índices da lista indices
print(array3[indices3])

[[[[-1  3  2]
   [ 5  1 -4]]]


 [[[13 14  1]
   [10 10  9]]]]


Exemplos em dimensões mais altas seguem o mesmo padrão apresentado acima. No entanto, inicialmente pode ser um pouco desafiador localizar elementos específicos, matrizes, submatrizes ou linhas/colunas de submatrizes, devido à complexidade adicional associada a arrays de dimensões mais altas.

## <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 22px;"><strong>21.3 Operações Matemáticas Básicas Com Arrays (Matrizes)</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

Apresentaremos a seguir algumas das operações mais comuns realizadas com matrizes.

#### *Exemplo 1: Soma e subtração de matrizes*

In [43]:
import numpy as np

# Definir dois arrays de dimensão 3 (matrizes 3x3)
matrix1 = np.array([[1, 1, 3],
                    [4, 4, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 3, 7],
                    [6, -1, 4],
                    [-3, 2, 1]])

In [44]:
# Somar os dois arrays como se fossem matrizes
result_sum = matrix1 + matrix2

print("Soma das matrizes:")
print(result_sum)

Soma das matrizes:
[[10  4 10]
 [10  3 10]
 [ 4 10 10]]


In [45]:
# Subtraindo os dois arrays como se fossem matrizes
result_sub = matrix1 - matrix2

print("Subtração das matrizes:")
print(result_sub)

Subtração das matrizes:
[[-8 -2 -4]
 [-2  5  2]
 [10  6  8]]


#### *Exemplo 2: Produto de matrizes*

In [46]:
import numpy as np

array1 = np.array([[1, 1], 
                   [2, 3]])

array2 = np.array([[2, 3], 
                   [1, 8]])

In [47]:
# Multiplicar os dois arrays como se fossem matrizes
dot_product = np.dot(array1, array2)

print("Produto das matrizes:")
print(dot_product)

Produto das matrizes:
[[ 3 11]
 [ 7 30]]


A multiplicação dos dois arrays usando a função **np.dot()** é dada por:

$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
\end{bmatrix} \cdot \begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
\end{bmatrix} =
\begin{bmatrix}
a_{11} \cdot b_{11} + a_{12} \cdot b_{21} & a_{11} \cdot b_{12} + a_{12} \cdot b_{22} \\
a_{21} \cdot b_{11} + a_{22} \cdot b_{21} & a_{21} \cdot b_{12} + a_{22} \cdot b_{22} \\
\end{bmatrix}
$$

Considerando

$$
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22} \\
\end{bmatrix}
=
\begin{bmatrix}
1 & 1 \\
2 & 3 \\
\end{bmatrix} \ \ \ e \ \ \ 
\begin{bmatrix}
b_{11} & b_{12} \\
b_{21} & b_{22} \\
\end{bmatrix}
=
\begin{bmatrix}
2 & 3 \\
1 & 8 \\
\end{bmatrix}
$$

temos:

$$
\begin{bmatrix}
1 & 1 \\
2 & 3 \\
\end{bmatrix} \cdot \begin{bmatrix}
2 & 3 \\
1 & 8 \\
\end{bmatrix} =
\begin{bmatrix}
1 \cdot 2 + 1 \cdot 1 & 1 \cdot 3 + 1 \cdot 8 \\
2 \cdot 2 + 3 \cdot 1 & 2 \cdot 3 + 3 \cdot 8 \\
\end{bmatrix}
$$

Agora, vamos calcular cada elemento da matriz resultante:

$$
\begin{align*}
1 \cdot 2 + 1 \cdot 1 & = 2 + 1 = 3 \\
1 \cdot 3 + 1 \cdot 8 & = 3 + 8 = 11 \\
2 \cdot 2 + 3 \cdot 1 & = 4 + 3 = 7 \\
2 \cdot 3 + 3 \cdot 8 & = 6 + 24 = 30 \\
\end{align*}
$$

Portanto, a matriz resultante da multiplicação é:

$$
\begin{bmatrix}
3 & 11 \\
7 & 30 \\
\end{bmatrix}
$$

Assim, a multiplicação das matrizes dadas resulta na matriz acima.



#### *Exemplo 3: Transposta de uma matriz*

In [49]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])

In [50]:
# Calcular a matriz transposta
transposed_array = np.transpose(array)

print("Matriz original:")
print(array)

print("Matriz transposta:")
print(transposed_array)

Matriz original:
[[1 2 3]
 [4 5 6]]
Matriz transposta:
[[1 4]
 [2 5]
 [3 6]]


#### *Exemplo 4: Inversa de matrizes*

In [51]:
import numpy as np

# Definir dois arrays de dimensão 2 (matrizes 2x2)
matrix = np.array([[1, 2],
                   [2, 3]])

In [52]:
# Calcular a inversa da soma das matrizes
result_inverse = np.linalg.inv(matrix)

print("Matriz original:")
print(matrix)

print("Matriz inversa:")
print(result_inverse)

Matriz original:
[[1 2]
 [2 3]]
Matriz inversa:
[[-3.  2.]
 [ 2. -1.]]


Testando...

In [53]:
print(np.dot(matrix,result_inverse))

[[1. 0.]
 [0. 1.]]


## <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 22px;"><strong>21.4 Funções Associadas a Arrays</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

Apresentaremos a seguir diversas funções e exemplos associados a arrays. As funções marcadas com $^{*}$ são consideradas mais técnicas.

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 1</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### all()

Retorna True se todos os elementos da array satisfazem uma condição, caso contrário, retorna False.

In [54]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])

print(np.all(array1 > 0))

True


In [55]:
array2 = np.array([1, 2, -3, 4, 5])

print(np.all(array2 > 0))

False


#### any()

Retorna True se pelo menos um elemento da array satisfaz uma condição, caso contrário, retorna False.

In [56]:
import numpy as np

array1 = np.array([1, 2, 3, 4, -5])

print(np.any(array1 > 0))

True


In [57]:
array2 = np.array([-1, -2, -3, -4, -5])

print(np.any(array2 > 0))

False


#### argmax()

Retorna o índice do maior elemento na array.

In [ ]:
import numpy as np

array = np.array([10, 5, 20, 30, 15])

print(np.argmax(array))

In [ ]:
print(array[3])

#### argmin()

Retorna o índice do menor elemento na array.

In [ ]:
import numpy as np

array = np.array([10, 5, 20, 15, 30])

print(np.argmin(array))

In [ ]:
print(array[1])

#### argpartition()

Retorna um array de índices que particiona a array em relação a um valor específico.

In [ ]:
import numpy as np

array = np.array([10, 5, 20, 15, 30]) # 5(0),10(1),15(2),20(3),30(4)

indices = np.argpartition(array, 2)

print(indices)

A saída [1 0 3 2 4] significa que os índices da array original foram reorganizados com base na aplicação da função argpartition do NumPy com o valor 2 como argumento.

A função argpartition particiona a array de tal forma que os primeiros elementos são os menores valores (2 neste caso) em uma ordem não especificada, seguidos pelos demais elementos em qualquer ordem. Os índices resultantes são retornados como uma nova array.

Aqui está uma explicação dos índices na saída [1 0 3 2 4]:

- O menor valor é 5, que estava originalmente na posição 1 da array.
- O segundo menor valor é 10, que estava originalmente na posição 0 da array.
- O terceiro menor valor é 15, que estava originalmente na posição 3 da array.
- O quarto menor valor é 20, que estava originalmente na posição 2 da array.
- O quinto menor valor é 30, que estava originalmente na posição 4 da array.

Portanto, a saída [1 0 3 2 4] representa os índices que correspondem à nova ordem da array após a aplicação da função argpartition. Vale ressaltar que essa função não classifica a array inteira em ordem crescente ou decrescente, mas garante que os menores valores estejam nas primeiras posições, sem especificar a ordem exata dos demais elementos. **Teste mais valores de n, no argumento (array,n), para entender!**

#### argsort()

Retorna os índices que ordenam a array em ordem crescente.

In [ ]:
import numpy as np

array = np.array([10, 5, 20, 15, 30]) # 5(0),10(1),15(2),20(3),30(4)

indices = np.argsort(array)

print(indices)

#### astype()

Retorna uma cópia da array com um tipo de dado especificado.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])

array1_float = array1.astype(float)

print(array1)
print(array1_float)

In [ ]:
array2 = np.array([1.3, 2.1, 3, 4.15, 5])

array2_int = array2.astype(int)

print(array2)
print(array2_int)

In [ ]:
array3 = np.array([1.3, 2.1, 3, 4.15, 5])

array3_str = array3.astype(str)

print(array3)
print(array3_str)

#### base()

Retorna o objeto de memória subjacente da array.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])

In [ ]:
array2 = array1[1:4]  # Cria uma visualização da array1

print(array2)

In [ ]:
print(array2.base)

In [ ]:
print(array1.base)

#### byteswap()*

Retorna uma cópia da array com a ordem dos bytes invertida. *Esta é considerada uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([0, 1, 2, 3, 4], dtype=np.int16)

array_byteswap = array.byteswap()

print(array_byteswap)

Vamos entender a saída para cada elemento do array original:

0 em int16 é representado em bytes como 00 00. Invertendo os bytes, ainda obtemos 00 00, que é 0.

1 em int16 é representado como 00 01. Invertendo os bytes, obtemos 01 00, que é 256.

2 em int16 é representado como 00 02. Invertendo os bytes, obtemos 02 00, que é 512.

3 em int16 é representado como 00 03. Invertendo os bytes, obtemos 03 00, que é 768.

4 em int16 é representado como 00 04. Invertendo os bytes, obtemos 04 00, que é 1024.

#### choose()

Constrói uma array a partir de uma lista de arrays selecionadas usando um índice.

In [ ]:
import numpy as np

# Define os arrays de seleção
selecao = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# Define o array de índices
indices = np.array([0, 2, 1])

# Usa a função choose()
resultado = np.choose(indices, selecao)

print(resultado)

Considerando índices [n$_{i_{1}}$,n$_{i_{2}}$,...,$,$n$_{i_{k}}$] seleciona-se o primeiro elemento do array $i_{1}$, o segundo elemento do array $i_{2}$,..., k-ésimo elemento do array $i_{k}$. Para entender melhor, acompanhe os próximos exemplos.

In [ ]:
selecao = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

indices = np.array([1, 1, 1])

resultado1 = np.choose(indices, selecao)

print(resultado1)

In [ ]:
selecao = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

indices = np.array([0, 1, 0])

resultado2 = np.choose(indices, selecao)

print(resultado2)

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 2</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### clip()

Limita os valores da array entre um intervalo definido.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5,-1])
array_clipped = np.clip(array, 2, 4)
print(array_clipped)

#### compress()

Retorna uma array com apenas os elementos selecionados por uma máscara booleana.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

mask = np.array([True, False, True, False, True])

array_compressed = np.compress(mask, array)

print(array_compressed)

#### conj() e conjugate()

Retorna o complexo conjugado de um array. O complexo conjugado de um número da forma $a + bj$ é dado por $a - bj$ e um número da forma $a - bj$ é dado por $a + bj$.

In [ ]:
import numpy as np

array = np.array([1 + 2j, 3 - 4j, -5 + 6j])
array_conjugate = np.conjugate(array)
print(array_conjugate)

#### copy()

A função copy cria uma cópia profunda (deep copy) de uma array. A cópia é independente da array original, o que significa que qualquer modificação feita em uma das arrays não afetará a outra.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = array1.copy()
array2[0] = 5

print(array1)
print(array2)


#### ctypes()

A função ctypes retorna um objeto ctypes que permite o acesso direto aos dados de uma array como um buffer de memória bruto. Isso pode ser útil para integração com outros módulos ou bibliotecas escritas em C. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype=np.int32)
ctypes_data = array.ctypes.data

print(ctypes_data)

O número 2184932005136 (associado ao array[1,2,3]) ou qualquer outro número que possa aparecer ao executar o código é o endereço de memória no qual o primeiro byte do array numpy está armazenado no seu sistema. Este endereço é específico para a execução atual do código e pode variar em diferentes execuções ou em diferentes sistemas/máquinas.

#### cumprod()

A função cumprod retorna um array contendo os produtos acumulados dos elementos da array ao longo de um determinado eixo.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 4])
cumprod_array = np.cumprod(array)

print(cumprod_array)

#### cumsum()

A função cumsum retorna um array contendo as somas acumuladas dos elementos da array ao longo de um determinado eixo.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4])
cumsum_array = np.cumsum(array)

print(cumsum_array)

#### data()

A função data retorna um buffer de memória que contém os elementos da array. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype=np.float64)
array_data = array.data

print(array_data)

A saída <memory at 0x000001FCBA869A80> é uma representação desse objeto de buffer. A parte 0x000001FCBA869A80 é um endereço de memória hexadecimal e aponta para onde, na memória, o primeiro byte do array numpy está armazenado. Assim como antes, este endereço é específico para a execução atual do código e pode variar em diferentes execuções ou em diferentes sistemas/máquinas.

#### diagonal()

A função diagonal retorna uma view dos elementos na diagonal principal de uma array.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
diagonal_array = np.diagonal(array)

print(diagonal_array)

In [ ]:
import numpy as np

array = np.array([[1, 2], 
                  [4, 5], 
                  [7, 8]])
diagonal_array = np.diagonal(array)

print(diagonal_array)

#### dot()

A função dot realiza a multiplicação matricial entre duas arrays.

In [ ]:
import numpy as np

array1 = np.array([[1, 1], 
                   [2, 3]])
array2 = np.array([[2, 3], 
                   [1, 8]])
dot_product = np.dot(array1, array2)

print(dot_product)

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 3</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### dtype()

A função np.array() do NumPy cria um array NumPy a partir de uma sequência (como uma lista ou tupla) e permite especificar explicitamente o tipo de dados (dtype) dos elementos internos do array.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3], dtype=np.float64)
array_dtype1 = array1.dtype

print(array_dtype1)
print(array1)

In [ ]:
import numpy as np

array2 = np.array(['1', '2', '3'], dtype=np.float64)
array_dtype2 = array2.dtype

print(array_dtype2)
print(array2)

#### dump()

A função dump salva a array em um arquivo binário. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np
import pickle

array = np.array([1, 2, 3])
with open('array_data.bin', 'wb') as file:
    pickle.dump(array, file)


Podemos reinterpretar a saída com o código a seguir:

In [ ]:
import numpy as np
import pickle

# Carregar o array NumPy a partir do arquivo binário
with open('array_data.bin', 'rb') as file:
    loaded_array = pickle.load(file)

# Agora, 'loaded_array' contém o array NumPy original
print(loaded_array)

#### fill() 

A função fill preenche todos os elementos da array com um valor específico.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array.fill(0)

print(array)

#### flags()

A função flags retorna um objeto que fornece informações sobre as propriedades da array, como a memória utilizada e o layout dos elementos. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array_flags = array.flags

print(array_flags)

#### flat()

 A função flat retorna um iterador que percorre todos os elementos da array como se fosse um único array unidimensional.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
for element in array.flat:
    print(element)


#### flatten()

A função flatten retorna uma cópia da array original em uma nova array unidimensional. Os elementos são copiados na ordem da primeira dimensão, ou seja, é realizada uma achatamento completo.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
flattened_array = array.flatten()
print(flattened_array)

#### getfield()

A função getfield retorna um campo específico de cada elemento da array. O campo é especificado pelo nome do dtype.

In [ ]:
import numpy as np

array = np.array([(1, 2), (3, 4)], dtype=[('x', np.float32), ('y', np.float32)])
x_values = array['x']
print(x_values)


In [ ]:
y_values = array['y']
print(y_values)

No código acima, dtype=[('x', np.float32), ('y', np.float32)] especifica que os campos 'x' e 'y' do array são do tipo float32. Você pode alterar 'np.float32' para qualquer outro tipo suportado pelo NumPy, como np.int32, np.float64, np.uint16, etc., conforme necessário para seus requisitos. Certifique-se apenas de que o tipo especificado seja compatível com os valores que você deseja armazenar no array.

#### imag()

A função imag retorna a parte imaginária dos elementos da array.

In [ ]:
import numpy as np

array1 = np.array([1 + 2, 3 + 4j, 5 - 6j])
imaginary_part1 = array1.imag
print(imaginary_part1)

In [ ]:
array2 = np.array([1, 3, 5])
imaginary_part2 = array2.imag
print(imaginary_part2)

#### item()

A função item retorna um único elemento da array como um objeto Python.

In [ ]:
import numpy as np

array = np.array([3, -2, 4])
first_element = array.item(0)
print(first_element)

#### itemset()

A função itemset atribui um valor a um único elemento da array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array.itemset(1, -3)
print(array) 

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 4</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### itemsize()

A função itemsize retorna o número de bytes usado para armazenar cada elemento da array. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype=np.int32)
size_of_element = array.itemsize
print(size_of_element)

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype=np.float64)
size_of_element = array.itemsize
print(size_of_element)


#### max()

A função max retorna o valor máximo da array ou ao longo de um determinado eixo.

In [ ]:
import numpy as np

array = np.array([1, 2, -3])
maximum_value = array.max()
print(maximum_value)

In [ ]:
matrix = np.array([[1,   8, 3],
                   [9,  11, 7],
                   [10,  1, 4],
                   [-1,  2, 3]])
maximum_values_along_axis0 = matrix.max(axis=0)
maximum_values_along_axis1 = matrix.max(axis=1)

print("Valor máximo ao longo do eixo 0:", maximum_values_along_axis0)
print("Valor máximo ao longo do eixo 1:", maximum_values_along_axis1)


#### mean()

A função mean retorna a média dos elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array_mean = np.mean(array)
print(array_mean)

#### min() 

A função min retorna o valor mínimo da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([5, 3, 8, 1, 6])
array_min = np.min(array)
print(array_min)

In [ ]:
matrix = np.array([[1,   8, 3],
                   [9,  11, 7],
                   [10,  1, 4],
                   [-1,  2, 3]])
manimum_values_along_axis0 = matrix.min(axis=0)
manimum_values_along_axis1 = matrix.min(axis=1)

print("Valor mínimo ao longo do eixo 0:", manimum_values_along_axis0)
print("Valor mínimo ao longo do eixo 1:", manimum_values_along_axis1)

#### nbytes()*

A função nbytes retorna o número total de bytes ocupados pela array. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
array_nbytes = array.nbytes
print(array_nbytes)


#### ndim()

A função ndim retorna o número de dimensões (ou eixos) da array.

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array_ndim = array1.ndim
print(array_ndim)

In [ ]:
array2 = np.array([[1, 2, 3], 
                  [4, 5, 6]])
array_ndim = array.ndim
print(array_ndim)

In [ ]:
array_3d = np.array([[[1, 2, 3], 
                      [4, 5, 6]], [[7, 8, 9], 
                                   [10, 11, 12]]])
array_3d_ndim = array_3d.ndim
print(array_3d_ndim)


#### newbyteorder()*

A função newbyteorder retorna uma nova array com a ordem dos bytes alterada. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3], dtype=np.int32)
new_byteorder_array = array.newbyteorder('big')
print(new_byteorder_array) 

#### nonzero()

A função nonzero retorna um array contendo os índices dos elementos não zero.

In [ ]:
import numpy as np

array = np.array([0, 2, 0, 4, 0])
nonzero_indices = np.nonzero(array)
print(nonzero_indices)

#### partition() 

A função partition retorna uma nova array com os elementos rearranjados de forma que os k menores elementos estejam antes dos k maiores elementos.

In [ ]:
import numpy as np

array = np.array([3, 1, 4, 1, 5, 9, 2, 6])
partitioned_array = np.partition(array, 1)
print(partitioned_array)

In [ ]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6])
partitioned_array = np.partition(array, 2)
print(partitioned_array)

In [ ]:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6])
partitioned_array = np.partition(array, 7)
print(partitioned_array)

#### prod()

A função prod retorna o produto dos elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([2, 3, 4])
array_prod = np.prod(array)
print(array_prod)

In [ ]:
matrix = np.array([[2, 3, 4],
                   [1, 2, 3]])
product_along_axis0 = np.prod(matrix, axis=0)
print("Produto ao longo do eixo 0:", product_along_axis0)

In [ ]:
matrix = np.array([[2, 3, 4],
                   [1, 2, 3]])
product_along_axis0 = np.prod(matrix, axis=1)
print("Produto ao longo do eixo 1:", product_along_axis0)

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 5</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### ptp()

A função ptp retorna a amplitude dos valores (diferença entre o valor máximo e mínimo) da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([5, -3, 8, -1, 6])
array_ptp = np.ptp(array)
print(array_ptp)

In [ ]:
matrix = np.array([[5, -3, 8],
                   [1, 6, 2],
                   [1, 3, 7]])
ptp_along_axis0 = np.ptp(matrix, axis=0)
print("Pico a Pico ao longo do eixo 0:", ptp_along_axis0)

In [ ]:
matrix = np.array([[5, -3, 8],
                   [1, 6, 2],
                   [1, 3, 7]])
ptp_along_axis1 = np.ptp(matrix, axis=1)
print("Pico a Pico ao longo do eixo 1:", ptp_along_axis1)

#### put()

A função put substitui os elementos da array pelos valores fornecidos em um array de índices.

In [ ]:
import numpy as np

array = np.array([-1, 0, 1, 2, 5])
indices = [1, 3]
np.put(array, indices, [10, 20])
print(array)


#### ravel()

A função ravel retorna uma array unidimensional que contém os elementos da array original.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
raveled_array = array.ravel()
print(raveled_array)

#### real()

A função real retorna a parte real dos elementos da array.

In [ ]:
import numpy as np

array = np.array([1 + 2j, -3 + 4j, 5 + 6j])
real_part = array.real
print(real_part)


In [ ]:
array = np.array([1, -3,6j])
real_part = array.real
print(real_part)

#### repeat()

A função repeat retorna uma nova array em que cada elemento é repetido um número especificado de vezes.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
repeated_array = np.repeat(array, 3)
print(repeated_array)

#### reshape()

A função reshape retorna uma nova array com a mesma quantidade de elementos, mas com uma nova forma (dimensão) especificada.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))
print(reshaped_array)

#### resize()

A função resize altera a forma (dimensão) de uma array existente, adicionando ou removendo elementos conforme necessário.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
resized_array = np.resize(array, (5,))
print(resized_array)

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
resized_array = np.resize(array, (3,))
print(resized_array)

#### round() 

A função round arredonda os elementos da array para o número especificado de casas decimais.

In [ ]:
import numpy as np

array = np.array([1.234, 2.567, 3.792])
rounded_array = np.round(array, decimals=1)
print(rounded_array)


#### searchsorted() 

A função searchsorted retorna os índices onde os elementos da array devem ser inseridos para que a ordem da array seja mantida.

In [ ]:
import numpy as np

array = np.array([1, 3, 5, 7, 9])
indices = np.searchsorted(array, [4, 8]) # [1, 3, 4, 5, 7, 9] e [1, 3, 5, 7, 8, 9]
print(indices)

#### setflags()

A função setflags altera as configurações de sinalizadores (flags) de uma array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array.setflags(write=False)
print(array.flags.writeable)

In [ ]:
# Tentativa de modificar a array
array[0] = 10

print(array)
# Output: ValueError: assignment destination is read-only

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 6</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### shape()

A função shape retorna a forma (dimensão) da array como uma tupla de inteiros. Exemplo:

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
array_shape = array.shape
print(array_shape)

#### size()

A função size retorna o número total de elementos da array.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
array_size = array.size
print(array_size)

#### sort()

A função sort ordena os elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([5, 2, 8, 1, 6])
sorted_array = np.sort(array)
print(sorted_array)

#### squeeze()

A função squeeze remove dimensões de tamanho 1 de uma array.

In [ ]:
import numpy as np

# Criar um array com dimensão 1x3x1
array = np.array([[[1], [2], [3]]])

# Usar squeeze() para remover dimensões de tamanho 1
result = np.squeeze(array)

print("Array original:")
print(array)
print("Array após squeeze():")
print(result)


In [ ]:
import numpy as np

array = np.array([[[1,2]], [[2,-1]], [[3,5]]])

result = np.squeeze(array)

print("Array original:")
print(array)
print("Array após squeeze():")
print(result)

#### std()

A função std retorna o desvio padrão dos elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array_std = np.std(array)
print(array_std)

#### strides()

A função strides retorna uma tupla de inteiros que descreve o número de bytes que a array avança em cada dimensão. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
array_strides = array.strides
print(array_strides)

#### sum()

A função sum retorna a soma dos elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Somar ao longo do eixo 0 (soma coluna a coluna)
sum_along_axis0 = np.sum(matrix, axis=0)

# Somar ao longo do eixo 1 (soma linha a linha)
sum_along_axis1 = np.sum(matrix, axis=1)

print("Soma ao longo do eixo 0:", sum_along_axis0)
print("Soma ao longo do eixo 1:", sum_along_axis1)


#### swapaxes() 

A função swapaxes retorna uma nova array com os eixos permutados.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
swapped_array = np.swapaxes(array, 0, 1)
print(swapped_array)

#### take()

A função take retorna uma nova array com os elementos especificados pelos índices fornecidos.

In [ ]:
import numpy as np

array = np.array([1, -1, 3, 7, 5])
indices = [1, 3]
taken_array = np.take(array, indices)
print(taken_array)

#### tobytes()

Retorna uma representação em string compacta da array. *Esta é uma função mais técnica.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array_bytes = array.tobytes()

print(array_bytes)

### <div style="margin-top: -20px;">
<hr style="border: 2px solid blue;">

<font color='blue'><span style="font-size: 18px;"><strong>21.4.1 Funções Associadas a Arrays - Parte 7</strong></span></font>

<hr style="border: 2px solid blue;">
</div>

#### tofile()

O método tofile grava os elementos da array em um arquivo binário.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array.tofile('data.bin')

Acessando o arquivo:

In [ ]:
import numpy as np

# Criar um array NumPy
array = np.array([1, 2, 3])

# Salvar o array em um arquivo binário
array.tofile('data.bin')

# Carregar os dados do arquivo binário em um novo array
loaded_array = np.fromfile('data.bin', dtype=array.dtype)

print("Dados carregados do arquivo:")
print(loaded_array)

#### tolist()

O método tolist retorna uma lista Python contendo os elementos da array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array_list = array.tolist()

print(array)
print(array_list)

#### trace()

A função trace retorna a soma dos elementos da diagonal principal da array.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
array_trace = np.trace(array)
print(array_trace)


#### transpose()

A função transpose retorna uma nova array com os eixos permutados.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
transposed_array = np.transpose(array)
print(transposed_array)

#### var()

A função var retorna a variância dos elementos da array ao longo de um determinado eixo ou de toda a array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
array_var = np.var(array)
print(array_var)

#### view()*

O método view retorna uma nova array que é uma visualização (view) da array original, compartilhando os mesmos dados, mas com uma nova forma ou tipo de dado. *Este é um método mais técnico.*

In [ ]:
import numpy as np

array = np.array([1, 2, 3])
array_view = array.view(dtype=np.float32)
print(array_view)

In [ ]:
array = np.array([1.0, 2.0])
array_view = array.view(dtype=np.float32)
print(array_view)